db:
  image: mysql:8.0
  platform: linux/arm64
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: opencats
    MYSQL_USER: opencats
    MYSQL_PASSWORD: opencats
  volumes:
    - db_data:/var/lib/mysql